//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendFitAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditPrice
    {
        public int EditPriceId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string OptionToEditPrice { get; set; }
    }
}
