//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendFitAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FriendFitDBEntities : DbContext
    {
        public FriendFitDBEntities()
            : base("name=FriendFitDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FriendsInvitation> FriendsInvitations { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<UserToken> UserTokens { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<Logo> Logoes { get; set; }
        public virtual DbSet<EditPrice> EditPrices { get; set; }
        public virtual DbSet<Link> Links { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<ActualDistanceExercise> ActualDistanceExercises { get; set; }
        public virtual DbSet<ActualExcerciseSet> ActualExcerciseSets { get; set; }
        public virtual DbSet<ActualFreeTextExercise> ActualFreeTextExercises { get; set; }
        public virtual DbSet<ActualLevelExercise> ActualLevelExercises { get; set; }
        public virtual DbSet<ActualRepsExercise> ActualRepsExercises { get; set; }
        public virtual DbSet<ActualTimedExercise> ActualTimedExercises { get; set; }
        public virtual DbSet<ActualWeightExercise> ActualWeightExercises { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<DeliveryTypeMaster> DeliveryTypeMasters { get; set; }
        public virtual DbSet<DeviceMaster> DeviceMasters { get; set; }
        public virtual DbSet<DistanceExercise> DistanceExercises { get; set; }
        public virtual DbSet<DistanceExerciseSet> DistanceExerciseSets { get; set; }
        public virtual DbSet<DurationMaster> DurationMasters { get; set; }
        public virtual DbSet<ExcerciseSet> ExcerciseSets { get; set; }
        public virtual DbSet<Exercise> Exercises { get; set; }
        public virtual DbSet<ExerciseTypeMaster> ExerciseTypeMasters { get; set; }
        public virtual DbSet<FreeTextExercise> FreeTextExercises { get; set; }
        public virtual DbSet<FrequencyMaster> FrequencyMasters { get; set; }
        public virtual DbSet<LevelExercise> LevelExercises { get; set; }
        public virtual DbSet<MailTimeLog> MailTimeLogs { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PurchaseProductsList> PurchaseProductsLists { get; set; }
        public virtual DbSet<Recurrence> Recurrences { get; set; }
        public virtual DbSet<RepsExercise> RepsExercises { get; set; }
        public virtual DbSet<ScheduleActualDistanceExercise> ScheduleActualDistanceExercises { get; set; }
        public virtual DbSet<ScheduleActualExcerciseSet> ScheduleActualExcerciseSets { get; set; }
        public virtual DbSet<ScheduleActualFreeTextExercise> ScheduleActualFreeTextExercises { get; set; }
        public virtual DbSet<ScheduleActualLevelExercise> ScheduleActualLevelExercises { get; set; }
        public virtual DbSet<ScheduleActualRepsExercise> ScheduleActualRepsExercises { get; set; }
        public virtual DbSet<ScheduleActualTimedExercise> ScheduleActualTimedExercises { get; set; }
        public virtual DbSet<ScheduleActualWeightExercise> ScheduleActualWeightExercises { get; set; }
        public virtual DbSet<ScheduleExercise> ScheduleExercises { get; set; }
        public virtual DbSet<ScheduleGoalDistanceExercise> ScheduleGoalDistanceExercises { get; set; }
        public virtual DbSet<ScheduleGoalExcerciseSet> ScheduleGoalExcerciseSets { get; set; }
        public virtual DbSet<ScheduleGoalFreeTextExercise> ScheduleGoalFreeTextExercises { get; set; }
        public virtual DbSet<ScheduleGoalLevelExercise> ScheduleGoalLevelExercises { get; set; }
        public virtual DbSet<ScheduleGoalRepsExercise> ScheduleGoalRepsExercises { get; set; }
        public virtual DbSet<ScheduleGoalTextExercise> ScheduleGoalTextExercises { get; set; }
        public virtual DbSet<ScheduleGoalTimedExercise> ScheduleGoalTimedExercises { get; set; }
        public virtual DbSet<ScheduleGoalWeightExercise> ScheduleGoalWeightExercises { get; set; }
        public virtual DbSet<ScheduleWeeklyMaster> ScheduleWeeklyMasters { get; set; }
        public virtual DbSet<StatusMaster> StatusMasters { get; set; }
        public virtual DbSet<SubscriptionTypeMaster> SubscriptionTypeMasters { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblPrice> tblPrices { get; set; }
        public virtual DbSet<TextExercise> TextExercises { get; set; }
        public virtual DbSet<TimedExercise> TimedExercises { get; set; }
        public virtual DbSet<WeightExercise> WeightExercises { get; set; }
        public virtual DbSet<WorkOut> WorkOuts { get; set; }
        public virtual DbSet<WorkOutSchedule> WorkOutSchedules { get; set; }
    
        public virtual ObjectResult<GetTransaction_Result> GetTransaction()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTransaction_Result>("GetTransaction");
        }
    
        public virtual ObjectResult<GetTransactionForFriend_Result> GetTransactionForFriend()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTransactionForFriend_Result>("GetTransactionForFriend");
        }
    
        public virtual ObjectResult<GetTransactionForUser_Result> GetTransactionForUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTransactionForUser_Result>("GetTransactionForUser");
        }
    
        public virtual ObjectResult<GetTransactionForUser1_Result> GetTransactionForUser1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTransactionForUser1_Result>("GetTransactionForUser1");
        }
    
        public virtual ObjectResult<GetTransactionForUser11_Result> GetTransactionForUser11()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTransactionForUser11_Result>("GetTransactionForUser11");
        }
    }
}
