//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendFitAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public int LinkId { get; set; }
        public string Link1 { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string LinkType { get; set; }
        public Nullable<int> NoOfTimeAcc { get; set; }
    }
}
