//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendFitAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseProductsList
    {
        public int Id { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public string SKU { get; set; }
        public string Name { get; set; }
        public string Quantity { get; set; }
        public string Price { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> RowInsert { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
