//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendFitAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int transdetailid { get; set; }
        public int transid { get; set; }
        public int paymentid { get; set; }
        public string IPAddress { get; set; }
        public string transactionType { get; set; }
        public string debitaccount { get; set; }
        public string creditaccount { get; set; }
        public decimal amount { get; set; }
        public bool isdebit { get; set; }
        public bool isactive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
