//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendFitAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOut
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOut()
        {
            this.Exercises = new HashSet<Exercise>();
        }
    
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateOfWorkout { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> FinishTime { get; set; }
        public string WorkoutNotes { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> Updatedate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> RowStatus { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> AutoFinishTime { get; set; }
        public Nullable<bool> ScheduleWorkout { get; set; }
        public Nullable<System.DateTime> Actual_StartTime { get; set; }
        public Nullable<long> ScheduleId { get; set; }
        public Nullable<int> SendSMSToUser { get; set; }
        public Nullable<int> SendSMSToFriends { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exercise> Exercises { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
