<%@ Page Language="C#" Inherits="AbleCommerce.Admin.Catalog.AddCategory" MasterPageFile="~/Admin/Admin.master" title="Add Category" CodeFile="AddCategory.aspx.cs" AutoEventWireup="True" %>
<asp:Content ID="MainContent" ContentPlaceHolderID="MainContent" Runat="Server">
<div class="pageHeader">
    <div class="caption">
    	<h1><asp:Localize ID="Caption" runat="server" Text="Add Category to {0}"></asp:Localize></h1>
       <div class="links">
        <asp:Button ID="FinishButton1" runat="server" Text="Finish" SkinID="SaveButton" OnClick="FinishButton_Click" />
		<asp:Button ID="CancelButton1" runat="server" Text="Cancel" SkinID="CancelButton" CausesValidation="False" OnClick="CancelButton_Click" />
      </div>
    </div>
</div>
<div class="content">
	<asp:ValidationSummary ID="ErrorSummary" runat="server" />
	<table cellspacing="0" class="inputForm">
        <tr>
            <th width="15%">
                <cb:ToolTipLabel ID="NameLabel" runat="server" Text="Name:" CssClass="toolTip" ToolTip="Name of the category."></cb:ToolTipLabel>
            </th>
            <td width="35%">
                <asp:TextBox ID="Name" runat="server" Text="" Columns="40" MaxLength="100"></asp:TextBox><span class="requiredField">*</span>
                <asp:RequiredFieldValidator ID="NameValidator" runat="server" Text="*" Display="Dynamic" ErrorMessage="Name is required." ControlToValidate="Name"></asp:RequiredFieldValidator>
            </td>
            <th>
                <cb:ToolTipLabel ID="VisibilityLabel" runat="server" Text="Visibility:" AssociatedControlID="Visibility" ToolTip="Public items are accessible and display in navigation and search results.  Hidden items are accessible only by direct link, and do not appear in navigation or search results.  Private items may not be accessed from the retail store."></cb:ToolTipLabel>
            </th>
            <td>
                <asp:DropDownList ID="Visibility" runat="server">
                    <asp:ListItem Value="0" Text="Public"></asp:ListItem>
                    <asp:ListItem Value="1" Text="Hidden"></asp:ListItem>
                    <asp:ListItem Value="2" Text="Private"></asp:ListItem>
                </asp:DropDownList>
            </td>
        </tr>
        <tr>
            <th>
                <cb:ToolTipLabel ID="ThumbnailUrlLabel" runat="server" Text="Thumbnail:" AssociatedControlId="ThumbnailUrl" ToolTip="Specifies the thumbnail image that may be used with this item on some display pages."></cb:ToolTipLabel>
            </th>
            <td>
                <asp:TextBox ID="ThumbnailUrl" runat="server" MaxLength="250" width="250px"></asp:TextBox>&nbsp;
                <asp:ImageButton ID="BrowseThumbnailUrl" runat="server" SkinID="FindIcon" AlternateText="Browse" />
            </td>
            <th>
                <cb:ToolTipLabel ID="ThumbnailAltTextLabel" runat="server" Text="Alt Text:" AssociatedControlId="ThumbnailAltText" ToolTip="Specifies the alternate text that should be set on the thumbnail image.  Leave blank to use the item name."></cb:ToolTipLabel>
            </th>
            <td>
                <asp:TextBox ID="ThumbnailAltText" runat="server" MaxLength="250"></asp:TextBox>&nbsp;
            </td>
        </tr>
        <tr>
            <th width="15%" valign="top">
                <cb:ToolTipLabel ID="CustomUrlLabel" runat="server" Text="Custom Url:" ToolTip="You can provide a custom URL to access your category. This URL will override the default one generated by system. The value provided should be a URL relative to the store directory. Absolute URLs are not supported."></cb:ToolTipLabel>
            </th>
            <td colspan="3" valign="top">
                <asp:TextBox ID="CustomUrl" runat="server" Width="250" MaxLength="150"></asp:TextBox>
                <cb:CustomUrlValidator ID="CustomUrlValidator" runat="server" ControlToValidate="CustomUrl" 
                    Text="*" FormatErrorMessage="The custom url has an invalid format."
                    DuplicateErrorMessage="This custom url is already used, please choose a unique value."></cb:CustomUrlValidator><br />
                <asp:Localize ID="CustomUrlExample" runat="server" Text="e.g. Fiction/Mystery.aspx"></asp:Localize>
            </td>
		</tr>
        <tr>
            <th valign="top">
                <asp:ImageButton ID="SummaryHtmlButton" runat="server" SkinID="HtmlIcon" AlternateText="Edit HTML" />
                <cb:ToolTipLabel ID="SummaryLabel" runat="server" Text="Summary:" ToolTip="A summary or introduction to the category, used by some category display pages to provide a description of the category to the customer."></cb:ToolTipLabel>
            </th>
            <td colspan="3">
                <cb:HtmlEditor ID="Summary" runat="server" Width="100%" Height="200px" ToolbarSet="Inline" MaxLength="1000" />
            </td>
        </tr>
        <tr>
            <th valign="top">
                <asp:ImageButton ID="DescriptionHtmlButton" runat="server" SkinID="HtmlIcon" AlternateText="Edit HTML" />
                <cb:ToolTipLabel ID="DescriptionLabel" runat="server" Text="Description:" ToolTip="This is used by some display pages to show a detailed description or HTML content on the category page."></cb:ToolTipLabel>
            </th>
            <td colspan="3">
                <cb:HtmlEditor ID="Description" runat="server" Width="100%" Height="200px" ToolbarSet="Inline" />
            </td>
        </tr>
        <tr>
            <th width="15%">
                <cb:ToolTipLabel ID="TitleLabel" runat="server" Text="Page Title:" CssClass="toolTip" ToolTip="Page title of the category. If not provided name will be used as page title."></cb:ToolTipLabel>
            </th>
            <td>
                <asp:TextBox ID="CategoryTitle" runat="server" Text="" Columns="40" MaxLength="100"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <th valign="top">
                <cb:ToolTipLabel ID="MetaDescriptionLabel" runat="server" Text="Meta Description:" ToolTip="Enter a description for this page for the META tag.  Some search engines will use this as the summary for your page. You do not need to enter any HTML meta tags - only enter the content you want to set in them."></cb:ToolTipLabel>
            </th>
            <td colspan="3">
                <asp:TextBox ID="MetaDescriptionValue" runat="server" Text="" TextMode="multiLine" Rows="5" Width="100%" MaxLength="300"></asp:TextBox><br />
                <asp:Label ID="MetaDescriptionCharCount" runat="server" Text="150"></asp:Label>
                <asp:Label ID="MetaDescriptionCharCountLabel" runat="server" Text="characters remaining"></asp:Label>
            </td>
        </tr>
        <tr>
            <th valign="top">
                <cb:ToolTipLabel ID="MetaKeywordsLabel" runat="server" Text="Meta Keywords:" ToolTip="Enter the keywords that describe your page for the META tag.  Enter single words separated by a comma, with a maxium of 1000 characters. You do not need to enter any HTML meta tags - only enter the content you want to set in them."></cb:ToolTipLabel>
            </th>
            <td colspan="3">
                <asp:TextBox ID="MetaKeywordsValue" runat="server" Text="" TextMode="multiLine" Rows="5" Width="100%" MaxLength="1000"></asp:TextBox><br />
                <asp:Label ID="MetaKeywordsCharCount" runat="server" Text="1000"></asp:Label>
                <asp:Label ID="MetaKeywordsCharCountLabel" runat="server" Text="characters remaining"></asp:Label>
            </td>
        </tr>
        <tr>
            <th valign="top">
                <cb:ToolTipLabel ID="HtmlHeadLabel" runat="server" Text="HTML Head:" ToolTip="Use this field for entring your custom data for HTML HEAD portion."></cb:ToolTipLabel>
            </th>
            <td colspan="3">
                <asp:TextBox ID="HtmlHead" runat="server" Text="" TextMode="multiLine" Rows="5" Width="100%"></asp:TextBox><br />
            </td>
        </tr>
        <tr>
            <th valign="top">
                <cb:ToolTipLabel ID="DisplayPageLabel" runat="server" Text="Display Page:" AssociatedControlId="DisplayPage" ToolTip="Specifies the script that will handle the display of this item."></cb:ToolTipLabel>
            </th>
            <td colspan="3">
                <asp:UpdatePanel ID="DisplayPageAjax" runat="server" UpdateMode="always">
                    <ContentTemplate>
                        <asp:DropDownList ID="DisplayPage" runat="server" AutoPostBack="true" OnSelectedIndexChanged="DisplayPage_SelectedIndexChanged" DataTextField="Name" DataValueField="Id" AppendDataBoundItems="true">
                            <asp:ListItem Text="Use store default" Value="0"></asp:ListItem>
                        </asp:DropDownList><br /><br />
                        <asp:Label ID="DisplayPageDescription" runat="Server" Text=""></asp:Label>
                    </ContentTemplate>
                </asp:UpdatePanel>
            </td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td colspan="3">                            
                <asp:Button ID="FinishButton" runat="server" Text="Finish" SkinID="SaveButton" OnClick="FinishButton_Click" />
				<asp:Button ID="CancelButton" runat="server" Text="Cancel" SkinID="CancelButton" CausesValidation="False" OnClick="CancelButton_Click" />
            </td>
        </tr>
    </table>
</div>
</asp:Content>